version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO
      - API_KEY=${API_KEY}
      - GOOGLE_CLIENT_SECRETS_JSON_PATH=/app/secrets/client_secret.json
      - GOOGLE_CREDENTIALS_JSON_PATH=/app/secrets/credentials.json
      - GOOGLE_SERVICE_ACCOUNT_PATH=/app/secrets/service_account.json
      - GOOGLE_CLOUD_PROJECT_ID=${GOOGLE_CLOUD_PROJECT_ID}
      - GOOGLE_PUBSUB_TOPIC_ID=${GOOGLE_PUBSUB_TOPIC_ID}
      - GOOGLE_PUBSUB_SUBSCRIPTION_ID=${GOOGLE_PUBSUB_SUBSCRIPTION_ID}
      - GMAIL_USER_ID=${GMAIL_USER_ID}
      - GMAIL_LABEL_URGENT=${GMAIL_LABEL_URGENT}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_CHANNEL_ID=${SLACK_CHANNEL_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./secrets:/app/secrets
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 