app = "email-triage-workflow-api"
primary_region = "iad" # Change to your preferred region
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "30s"
  interval = "15s"
  method = "GET"
  path = "/api/v1/health"
  protocol = "http"
  timeout = "10s"

[mounts]
  source = "email_triage_data"
  destination = "/app/data" 