app = "email-triage-workflow-api"
primary_region = "iad" # Change to your preferred region
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"

# Main app service
[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app_main"]

[[http_service.checks]]
  grace_period = "30s"
  interval = "15s"
  method = "GET"
  path = "/api/v1/health"
  protocol = "http"
  timeout = "10s"

# Define main app process group with data volume
[[services]]
  processes = ["app_main"]
  
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 8000
    handlers = ["http"]
    force_https = true

  [[services.mounts]]
    source = "email_triage_data"
    destination = "/app/data"

# Define secrets process group
[[services]]
  processes = ["app_secrets"]
  
  [[services.mounts]]
    source = "email_triage_secrets"
    destination = "/app/secrets"

# Define logs process group
[[services]]
  processes = ["app_logs"]
  
  [[services.mounts]]
    source = "email_triage_logs"
    destination = "/app/logs" 