app = "email-triage-workflow-api"
primary_region = "iad" # Change to your preferred region
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  DASHBOARD_PORT = "8501"

# Process definitions
[processes]
  app_main = "app_main"
  dashboard = "dashboard"
  metrics_collector = "metrics-collector-daemon"

# Main app service
[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 1
  processes = ["app_main"]

[[http_service.checks]]
  grace_period = "30s"
  interval = "15s"
  method = "GET"
  path = "/api/v1/health"
  protocol = "http"
  timeout = "10s"

# Dashboard service
[[services]]
  http_checks = []
  internal_port = 8501
  processes = ["dashboard"]
  protocol = "tcp"
  script_checks = []

  [[services.ports]]
    port = 8501
    handlers = ["http"]
    force_https = true

# Metrics collector service
[[services]]
  processes = ["metrics_collector"]

# Define main app process group with data volume
[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app_main"]
  protocol = "tcp"
  script_checks = []
  
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 8000
    handlers = ["http"]
    force_https = true

  [[services.mounts]]
    source = "email_triage_data"
    destination = "/app/data" 